// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 Alex Conesa
// See LICENSE file for details.

/**
 * @file gfx_bitmap.h
 * @brief Bitmap drawing functions for monochrome and indexed-color bitmaps
 *
 * All functions read from PROGMEM-safe byte arrays and draw directly to the
 * global gfx display instance.
 */

#pragma once
#include <cstdint>

namespace ungula::display
{

    /**
     * @brief Draw a 1-bit monochrome bitmap (no scaling)
     *
     * Thin wrapper around LovyanGFX drawBitmap(). Each byte packs 8 pixels,
     * MSB first. Set bits are drawn in the given color; clear bits are transparent.
     *
     * Generated by tools/pngToArray.py --mode mono.
     *
     * @param pos_x  Top-left X position
     * @param pos_y  Top-left Y position
     * @param bitmap PROGMEM byte array (1-bit packed pixels)
     * @param width  Bitmap width in pixels
     * @param height Bitmap height in pixels
     * @param color  Foreground color (RGB565)
     */
    void gfx_draw_bitmap(int pos_x, int pos_y, const uint8_t *bitmap, int width, int height, uint16_t color);

    /**
     * @brief Draw a 1-bit monochrome bitmap scaled to a different size
     *
     * Nearest-neighbor scaling. Each source byte packs 8 pixels, MSB first.
     * Set bits are drawn in the given color; clear bits are transparent.
     *
     * @param pos_x  Top-left X position
     * @param pos_y  Top-left Y position
     * @param bitmap PROGMEM byte array (1-bit packed pixels)
     * @param srcW   Source bitmap width in pixels
     * @param srcH   Source bitmap height in pixels
     * @param dstW   Destination width in pixels
     * @param dstH   Destination height in pixels
     * @param color  Foreground color (RGB565)
     */
    void gfx_draw_bitmap_scaled(int32_t pos_x, int32_t pos_y, const uint8_t *bitmap, int srcW, int srcH, int dstW,
                                int dstH, uint16_t color);

    /**
     * @brief Draw a 2-bit indexed bitmap with a caller-supplied color palette
     *
     * Each byte packs 4 pixels (2 bits each, MSB first).
     * Index 0 is transparent (skipped), indices 1-3 map to palette[1]-palette[3].
     *
     * Generated by tools/pngToArray.py --mode color.
     *
     * @param pos_x   Top-left X position
     * @param pos_y   Top-left Y position
     * @param data    PROGMEM byte array (2-bit packed pixels)
     * @param width   Image width in pixels
     * @param height  Image height in pixels
     * @param palette Array of 4 RGB565 colors (index 0 is ignored/transparent)
     */
    void gfx_draw_indexed_bitmap(int pos_x, int pos_y, const uint8_t *data, int width, int height,
                                 const uint16_t palette[4]);

} // namespace ungula::display
